// <auto-generated />
using System;
using MetaAdsAnalyzer.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MetaAdsAnalyzer.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404085712_AddPasswordHashAndWatchlist")]
    partial class AddPasswordHashAndWatchlist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.CampaignProductMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "CampaignId")
                        .IsUnique();

                    b.ToTable("campaign_product_map");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.ComputedMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BreakEvenRoas")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<decimal?>("Cpa")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("HoldRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("HookRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("MaxCpa")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MismatchRatio")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("NetMarginPct")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("NetProfitPerOrder")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RawInsightId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Roas")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("TargetCpa")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TargetRoas")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("RawInsightId");

                    b.ToTable("computed_metrics");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.Directive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DirectiveType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("HealthStatus")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "EntityId", "EntityType", "IsActive");

                    b.ToTable("directives");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cogs")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<decimal>("LtvMultiplier")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal>("PaymentFeePct")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("ReturnRatePct")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TargetMarginPct")
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.RawInsight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("AddToCart")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CpcLink")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Cpm")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CtrAll")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CtrLink")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateOnly>("DateStart")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateStop")
                        .HasColumnType("date");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EntityName")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<decimal>("Frequency")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long>("Impressions")
                        .HasColumnType("bigint");

                    b.Property<long>("InitiateCheckout")
                        .HasColumnType("bigint");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("LinkClicks")
                        .HasColumnType("bigint");

                    b.Property<string>("MetaCampaignId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("PurchaseValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("Purchases")
                        .HasColumnType("bigint");

                    b.Property<long>("Reach")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Spend")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("VideoAvgWatchTime")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("VideoP100")
                        .HasColumnType("bigint");

                    b.Property<long>("VideoP25")
                        .HasColumnType("bigint");

                    b.Property<long>("VideoP50")
                        .HasColumnType("bigint");

                    b.Property<long>("VideoP75")
                        .HasColumnType("bigint");

                    b.Property<long>("VideoPlay3s")
                        .HasColumnType("bigint");

                    b.Property<long>("VideoThruplay")
                        .HasColumnType("bigint");

                    b.Property<long>("ViewContent")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Level", "EntityId", "DateStart", "DateStop");

                    b.ToTable("raw_insights");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttributionWindow")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("MetaAccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaAdAccountId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("MetaTokenExpiresAt")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("MetaUserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MetaUserId")
                        .IsUnique()
                        .HasFilter("[MetaUserId] IS NOT NULL");

                    b.ToTable("users");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.WatchlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Level", "EntityId")
                        .IsUnique();

                    b.ToTable("watchlist_items");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.CampaignProductMap", b =>
                {
                    b.HasOne("MetaAdsAnalyzer.Core.Entities.Product", "Product")
                        .WithMany("CampaignProductMaps")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetaAdsAnalyzer.Core.Entities.User", "User")
                        .WithMany("CampaignProductMaps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.ComputedMetric", b =>
                {
                    b.HasOne("MetaAdsAnalyzer.Core.Entities.RawInsight", "RawInsight")
                        .WithMany("ComputedMetrics")
                        .HasForeignKey("RawInsightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RawInsight");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.Directive", b =>
                {
                    b.HasOne("MetaAdsAnalyzer.Core.Entities.User", "User")
                        .WithMany("Directives")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.Product", b =>
                {
                    b.HasOne("MetaAdsAnalyzer.Core.Entities.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.RawInsight", b =>
                {
                    b.HasOne("MetaAdsAnalyzer.Core.Entities.User", "User")
                        .WithMany("RawInsights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.WatchlistItem", b =>
                {
                    b.HasOne("MetaAdsAnalyzer.Core.Entities.User", "User")
                        .WithMany("WatchlistItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.Product", b =>
                {
                    b.Navigation("CampaignProductMaps");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.RawInsight", b =>
                {
                    b.Navigation("ComputedMetrics");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.User", b =>
                {
                    b.Navigation("CampaignProductMaps");

                    b.Navigation("Directives");

                    b.Navigation("Products");

                    b.Navigation("RawInsights");

                    b.Navigation("WatchlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
