// <auto-generated />
using System;
using MetaAdsAnalyzer.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MetaAdsAnalyzer.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.AdVideoLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AdName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("MetaAdAccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VideoId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MetaAdAccountId", "AdId")
                        .IsUnique();

                    b.ToTable("ad_video_links");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.CampaignProductMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "CampaignId")
                        .IsUnique();

                    b.ToTable("campaign_product_map");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.ComputedMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BreakEvenRoas")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("CompletionRatePct")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<decimal?>("Cpa")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CreativeScoreColor")
                        .HasColumnType("character varying(16)");

                    b.Property<string>("CreativeScoreLabel")
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("CreativeScoreTotal")
                        .HasColumnType("integer");

                    b.Property<decimal?>("HoldRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("HookRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("IsVideoCreative")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxCpa")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MismatchRatio")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("NetMarginPct")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("NetProfitPerOrder")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RawInsightId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Roas")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("TargetCpa")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TargetRoas")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("ThumbstopRatePct")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("Video15SecPerSpend")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("Video3SecPerSpend")
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("VideoMetricsUnavailable")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RawInsightId");

                    b.ToTable("computed_metrics");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.Directive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DirectiveType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("HealthStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Symptom")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "EntityId", "EntityType", "IsActive");

                    b.ToTable("directives");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cogs")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<decimal>("LtvMultiplier")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<decimal>("PaymentFeePct")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("ReturnRatePct")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TargetMarginPct")
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.RawInsight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("AddToCart")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CpcLink")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Cpm")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CtrAll")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CtrLink")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateOnly>("DateStart")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateStop")
                        .HasColumnType("date");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EntityName")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<decimal>("Frequency")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long>("Impressions")
                        .HasColumnType("bigint");

                    b.Property<long>("InitiateCheckout")
                        .HasColumnType("bigint");

                    b.Property<long>("LandingPageViews")
                        .HasColumnType("bigint");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("LinkClicks")
                        .HasColumnType("bigint");

                    b.Property<string>("MetaAdAccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AttributionWindow")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MetaAdsetId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MetaCampaignId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("PurchaseValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("Purchases")
                        .HasColumnType("bigint");

                    b.Property<long>("Reach")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Spend")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<long>("Video15Sec")
                        .HasColumnType("bigint");

                    b.Property<long>("Video30Sec")
                        .HasColumnType("bigint");

                    b.Property<decimal>("VideoAvgWatchTime")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("VideoP100")
                        .HasColumnType("bigint");

                    b.Property<long>("VideoP25")
                        .HasColumnType("bigint");

                    b.Property<long>("VideoP50")
                        .HasColumnType("bigint");

                    b.Property<long>("VideoP75")
                        .HasColumnType("bigint");

                    b.Property<long>("VideoP95")
                        .HasColumnType("bigint");

                    b.Property<long>("VideoPlay3s")
                        .HasColumnType("bigint");

                    b.Property<long>("VideoThruplay")
                        .HasColumnType("bigint");

                    b.Property<long>("ViewContent")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MetaAdAccountId", "Level", "EntityId", "DateStart", "DateStop");

                    b.ToTable("raw_insights");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.SavedReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AdName")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("AdsetId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AdsetName")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<decimal?>("AggregateHoldRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("AggregateHookRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int?>("AggregatePurchases")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AggregateRoas")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("AggregateSpend")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("AnalyzedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("CampaignId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CampaignName")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AdId", "AnalyzedAt");

                    b.ToTable("saved_reports");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.SavedReportSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("AfterHoldRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("AfterHookRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int?>("AfterPurchases")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AfterRoas")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("AfterSpend")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<decimal?>("BeforeHoldRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("BeforeHookRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int?>("BeforePurchases")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BeforeRoas")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("BeforeSpend")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DirectiveType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("ImpactMeasuredAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("MetaChangeDetected")
                        .HasColumnType("boolean");

                    b.Property<string>("MetaChangeMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("SavedReportId")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("SkippedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("SuggestionKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Symptom")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AppliedAt", "ImpactMeasuredAt");

                    b.HasIndex("SavedReportId", "SuggestionKey")
                        .IsUnique();

                    b.ToTable("saved_report_suggestions");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowsPdfExport")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowsWatchlist")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxLinkedMetaAdAccounts")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("subscription_plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowsPdfExport = false,
                            AllowsWatchlist = false,
                            Code = "standard",
                            Currency = "TRY",
                            Description = "Özet metrikler, kampanya eşlemesi, temel raporlar.",
                            DisplayName = "Standart",
                            IsActive = true,
                            MaxLinkedMetaAdAccounts = 2,
                            MonthlyPrice = 299m,
                            SortOrder = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            AllowsPdfExport = true,
                            AllowsWatchlist = true,
                            Code = "pro",
                            Currency = "TRY",
                            Description = "PDF dışa aktarma, takip listesi ve genişletilmiş kullanım.",
                            DisplayName = "Pro",
                            IsActive = true,
                            MaxLinkedMetaAdAccounts = 4,
                            MonthlyPrice = 599m,
                            SortOrder = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 4, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttributionWindow")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("MetaAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("MetaAdAccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("MetaTokenExpiresAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("MetaUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("PlanExpiresAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("integer");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MetaUserId")
                        .IsUnique()
                        .HasFilter("\"MetaUserId\" IS NOT NULL");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.UserMetaAdAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("MetaAdAccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MetaAdAccountId")
                        .IsUnique();

                    b.ToTable("user_meta_ad_accounts");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.VideoAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AggregatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<decimal?>("CompletionRateAvg")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateOnly>("FirstSeenDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("HoldRateAvg")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("HookRateAvg")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateOnly>("LastSeenDate")
                        .HasColumnType("date");

                    b.Property<string>("MetaAdAccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RepresentativeAdName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<decimal>("TotalPurchaseValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("TotalPurchases")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("TotalRoas")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("TotalSpend")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MetaAdAccountId", "VideoId")
                        .IsUnique();

                    b.ToTable("video_assets");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.WatchlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Level", "EntityId")
                        .IsUnique();

                    b.ToTable("watchlist_items");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.AdVideoLink", b =>
                {
                    b.HasOne("MetaAdsAnalyzer.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.CampaignProductMap", b =>
                {
                    b.HasOne("MetaAdsAnalyzer.Core.Entities.Product", "Product")
                        .WithMany("CampaignProductMaps")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetaAdsAnalyzer.Core.Entities.User", "User")
                        .WithMany("CampaignProductMaps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.ComputedMetric", b =>
                {
                    b.HasOne("MetaAdsAnalyzer.Core.Entities.RawInsight", "RawInsight")
                        .WithMany("ComputedMetrics")
                        .HasForeignKey("RawInsightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RawInsight");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.Directive", b =>
                {
                    b.HasOne("MetaAdsAnalyzer.Core.Entities.User", "User")
                        .WithMany("Directives")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.Product", b =>
                {
                    b.HasOne("MetaAdsAnalyzer.Core.Entities.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.RawInsight", b =>
                {
                    b.HasOne("MetaAdsAnalyzer.Core.Entities.User", "User")
                        .WithMany("RawInsights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.SavedReport", b =>
                {
                    b.HasOne("MetaAdsAnalyzer.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.SavedReportSuggestion", b =>
                {
                    b.HasOne("MetaAdsAnalyzer.Core.Entities.SavedReport", "SavedReport")
                        .WithMany("Suggestions")
                        .HasForeignKey("SavedReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavedReport");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.User", b =>
                {
                    b.HasOne("MetaAdsAnalyzer.Core.Entities.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Users")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.UserMetaAdAccount", b =>
                {
                    b.HasOne("MetaAdsAnalyzer.Core.Entities.User", "User")
                        .WithMany("UserMetaAdAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.VideoAsset", b =>
                {
                    b.HasOne("MetaAdsAnalyzer.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.WatchlistItem", b =>
                {
                    b.HasOne("MetaAdsAnalyzer.Core.Entities.User", "User")
                        .WithMany("WatchlistItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.Product", b =>
                {
                    b.Navigation("CampaignProductMaps");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.RawInsight", b =>
                {
                    b.Navigation("ComputedMetrics");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.SavedReport", b =>
                {
                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MetaAdsAnalyzer.Core.Entities.User", b =>
                {
                    b.Navigation("CampaignProductMaps");

                    b.Navigation("Directives");

                    b.Navigation("Products");

                    b.Navigation("RawInsights");

                    b.Navigation("UserMetaAdAccounts");

                    b.Navigation("WatchlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
